# -*- coding: utf-8 -*-

"""
This file is part of the PROPheT tool.

Copyright (C) 2016: MKLab <pmitzias@iti.gr; mriga@iti.gr; skontopo@iti.gr>

http://mklab.iti.gr/project/prophet-ontology-populator
https://github.com/MKLab-ITI/prophet

Licensed under the Apache License, Version 2.0 (the "License").
You may use this file in compliance with the License. 
For more details, see LICENCE file. 

"""

# Form implementation generated from reading ui file 'ui\SearchByClassWizard.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_WizardSearchByClassName(object):
    def setupUi(self, WizardSearchByClassName):
        WizardSearchByClassName.setObjectName(_fromUtf8("WizardSearchByClassName"))
        WizardSearchByClassName.resize(684, 513)
        WizardSearchByClassName.setFocusPolicy(QtCore.Qt.TabFocus)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8(":/images/search_by_class.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        WizardSearchByClassName.setWindowIcon(icon)
        WizardSearchByClassName.setWizardStyle(QtGui.QWizard.ClassicStyle)
        WizardSearchByClassName.setOptions(QtGui.QWizard.NoCancelButton)
        self.wizardPage1 = QtGui.QWizardPage()
        self.wizardPage1.setTitle(_fromUtf8(""))
        self.wizardPage1.setObjectName(_fromUtf8("wizardPage1"))
        self.gridLayout = QtGui.QGridLayout(self.wizardPage1)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.lblSearchClassInEM = QtGui.QLabel(self.wizardPage1)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lblSearchClassInEM.setFont(font)
        self.lblSearchClassInEM.setWordWrap(True)
        self.lblSearchClassInEM.setObjectName(_fromUtf8("lblSearchClassInEM"))
        self.gridLayout.addWidget(self.lblSearchClassInEM, 0, 0, 1, 1)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.comboBoxNamespaces = QtGui.QComboBox(self.wizardPage1)
        self.comboBoxNamespaces.setMaximumSize(QtCore.QSize(75, 16777215))
        self.comboBoxNamespaces.setAutoFillBackground(False)
        self.comboBoxNamespaces.setObjectName(_fromUtf8("comboBoxNamespaces"))
        self.horizontalLayout_2.addWidget(self.comboBoxNamespaces)
        self.lineEditSearchClassInEMClassName = QtGui.QLineEdit(self.wizardPage1)
        self.lineEditSearchClassInEMClassName.setObjectName(_fromUtf8("lineEditSearchClassInEMClassName"))
        self.horizontalLayout_2.addWidget(self.lineEditSearchClassInEMClassName)
        self.btnSearchClassInEM = QtGui.QPushButton(self.wizardPage1)
        self.btnSearchClassInEM.setEnabled(False)
        self.btnSearchClassInEM.setMaximumSize(QtCore.QSize(100, 16777215))
        self.btnSearchClassInEM.setDefault(False)
        self.btnSearchClassInEM.setObjectName(_fromUtf8("btnSearchClassInEM"))
        self.horizontalLayout_2.addWidget(self.btnSearchClassInEM)
        self.gridLayout.addLayout(self.horizontalLayout_2, 1, 0, 1, 1)
        self.treeWidgetSearchClassInEMInstancesResults = QtGui.QTreeWidget(self.wizardPage1)
        self.treeWidgetSearchClassInEMInstancesResults.setContextMenuPolicy(QtCore.Qt.CustomContextMenu)
        self.treeWidgetSearchClassInEMInstancesResults.setAlternatingRowColors(True)
        self.treeWidgetSearchClassInEMInstancesResults.setSelectionMode(QtGui.QAbstractItemView.ExtendedSelection)
        self.treeWidgetSearchClassInEMInstancesResults.setSelectionBehavior(QtGui.QAbstractItemView.SelectItems)
        self.treeWidgetSearchClassInEMInstancesResults.setObjectName(_fromUtf8("treeWidgetSearchClassInEMInstancesResults"))
        self.treeWidgetSearchClassInEMInstancesResults.header().setVisible(False)
        self.gridLayout.addWidget(self.treeWidgetSearchClassInEMInstancesResults, 2, 0, 1, 1)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.btnAllPage1 = QtGui.QPushButton(self.wizardPage1)
        self.btnAllPage1.setEnabled(False)
        self.btnAllPage1.setMaximumSize(QtCore.QSize(35, 16777215))
        self.btnAllPage1.setFlat(False)
        self.btnAllPage1.setObjectName(_fromUtf8("btnAllPage1"))
        self.horizontalLayout.addWidget(self.btnAllPage1)
        self.btnNonePage1 = QtGui.QPushButton(self.wizardPage1)
        self.btnNonePage1.setEnabled(False)
        self.btnNonePage1.setMaximumSize(QtCore.QSize(35, 16777215))
        self.btnNonePage1.setObjectName(_fromUtf8("btnNonePage1"))
        self.horizontalLayout.addWidget(self.btnNonePage1)
        self.lineEditSearchTreePage1 = QtGui.QLineEdit(self.wizardPage1)
        self.lineEditSearchTreePage1.setEnabled(False)
        self.lineEditSearchTreePage1.setObjectName(_fromUtf8("lineEditSearchTreePage1"))
        self.horizontalLayout.addWidget(self.lineEditSearchTreePage1)
        self.btnExpandAll = QtGui.QPushButton(self.wizardPage1)
        self.btnExpandAll.setEnabled(False)
        self.btnExpandAll.setMinimumSize(QtCore.QSize(53, 0))
        self.btnExpandAll.setMaximumSize(QtCore.QSize(53, 16777215))
        self.btnExpandAll.setObjectName(_fromUtf8("btnExpandAll"))
        self.horizontalLayout.addWidget(self.btnExpandAll)
        self.btnCollapseAll = QtGui.QPushButton(self.wizardPage1)
        self.btnCollapseAll.setEnabled(False)
        self.btnCollapseAll.setMinimumSize(QtCore.QSize(53, 0))
        self.btnCollapseAll.setMaximumSize(QtCore.QSize(53, 16777215))
        self.btnCollapseAll.setObjectName(_fromUtf8("btnCollapseAll"))
        self.horizontalLayout.addWidget(self.btnCollapseAll)
        self.lblSearching = QtGui.QLabel(self.wizardPage1)
        self.lblSearching.setObjectName(_fromUtf8("lblSearching"))
        self.horizontalLayout.addWidget(self.lblSearching)
        self.gridLayout.addLayout(self.horizontalLayout, 3, 0, 1, 1)
        self.treeWidgetSearchClassInEMInstancesResults.raise_()
        self.lblSearchClassInEM.raise_()
        self.comboBoxNamespaces.raise_()
        self.lineEditSearchClassInEMClassName.raise_()
        self.btnSearchClassInEM.raise_()
        self.lineEditSearchTreePage1.raise_()
        self.btnCollapseAll.raise_()
        self.btnExpandAll.raise_()
        WizardSearchByClassName.addPage(self.wizardPage1)
        self.wizardPage2 = QtGui.QWizardPage()
        self.wizardPage2.setObjectName(_fromUtf8("wizardPage2"))
        self.gridLayout_4 = QtGui.QGridLayout(self.wizardPage2)
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.comboBoxAvailableClassesInMM = QtGui.QComboBox(self.wizardPage2)
        self.comboBoxAvailableClassesInMM.setObjectName(_fromUtf8("comboBoxAvailableClassesInMM"))
        self.gridLayout_4.addWidget(self.comboBoxAvailableClassesInMM, 1, 0, 1, 3)
        self.lblPromptMessageInSearchClassInMM = QtGui.QLabel(self.wizardPage2)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lblPromptMessageInSearchClassInMM.setFont(font)
        self.lblPromptMessageInSearchClassInMM.setToolTip(_fromUtf8(""))
        self.lblPromptMessageInSearchClassInMM.setWordWrap(True)
        self.lblPromptMessageInSearchClassInMM.setObjectName(_fromUtf8("lblPromptMessageInSearchClassInMM"))
        self.gridLayout_4.addWidget(self.lblPromptMessageInSearchClassInMM, 0, 0, 1, 3)
        WizardSearchByClassName.addPage(self.wizardPage2)
        self.wizardPage3 = QtGui.QWizardPage()
        self.wizardPage3.setTitle(_fromUtf8(""))
        self.wizardPage3.setObjectName(_fromUtf8("wizardPage3"))
        self.gridLayout_2 = QtGui.QGridLayout(self.wizardPage3)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.lblShowPropertiesOfBothModels = QtGui.QLabel(self.wizardPage3)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lblShowPropertiesOfBothModels.setFont(font)
        self.lblShowPropertiesOfBothModels.setWordWrap(True)
        self.lblShowPropertiesOfBothModels.setObjectName(_fromUtf8("lblShowPropertiesOfBothModels"))
        self.gridLayout_2.addWidget(self.lblShowPropertiesOfBothModels, 0, 0, 1, 1)
        self.tableWidgetViewPropertiesOfBothModels = QtGui.QTableWidget(self.wizardPage3)
        self.tableWidgetViewPropertiesOfBothModels.setAutoFillBackground(False)
        self.tableWidgetViewPropertiesOfBothModels.setEditTriggers(QtGui.QAbstractItemView.NoEditTriggers)
        self.tableWidgetViewPropertiesOfBothModels.setAlternatingRowColors(True)
        self.tableWidgetViewPropertiesOfBothModels.setSelectionMode(QtGui.QAbstractItemView.NoSelection)
        self.tableWidgetViewPropertiesOfBothModels.setObjectName(_fromUtf8("tableWidgetViewPropertiesOfBothModels"))
        self.tableWidgetViewPropertiesOfBothModels.setColumnCount(2)
        self.tableWidgetViewPropertiesOfBothModels.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.tableWidgetViewPropertiesOfBothModels.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidgetViewPropertiesOfBothModels.setHorizontalHeaderItem(1, item)
        self.tableWidgetViewPropertiesOfBothModels.horizontalHeader().setCascadingSectionResizes(False)
        self.tableWidgetViewPropertiesOfBothModels.horizontalHeader().setDefaultSectionSize(300)
        self.tableWidgetViewPropertiesOfBothModels.horizontalHeader().setMinimumSectionSize(300)
        self.tableWidgetViewPropertiesOfBothModels.horizontalHeader().setStretchLastSection(True)
        self.gridLayout_2.addWidget(self.tableWidgetViewPropertiesOfBothModels, 1, 0, 1, 1)
        WizardSearchByClassName.addPage(self.wizardPage3)
        self.wizardPage4 = QtGui.QWizardPage()
        self.wizardPage4.setEnabled(True)
        self.wizardPage4.setTitle(_fromUtf8(""))
        self.wizardPage4.setObjectName(_fromUtf8("wizardPage4"))
        self.gridLayout_3 = QtGui.QGridLayout(self.wizardPage4)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.lblPopulatedInstances = QtGui.QLabel(self.wizardPage4)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lblPopulatedInstances.setFont(font)
        self.lblPopulatedInstances.setWordWrap(True)
        self.lblPopulatedInstances.setObjectName(_fromUtf8("lblPopulatedInstances"))
        self.gridLayout_3.addWidget(self.lblPopulatedInstances, 0, 0, 1, 1)
        self.treeWidgetSummary = QtGui.QTreeWidget(self.wizardPage4)
        self.treeWidgetSummary.setContextMenuPolicy(QtCore.Qt.CustomContextMenu)
        self.treeWidgetSummary.setAlternatingRowColors(True)
        self.treeWidgetSummary.setSelectionMode(QtGui.QAbstractItemView.NoSelection)
        self.treeWidgetSummary.setSelectionBehavior(QtGui.QAbstractItemView.SelectRows)
        self.treeWidgetSummary.setObjectName(_fromUtf8("treeWidgetSummary"))
        self.treeWidgetSummary.header().setVisible(False)
        self.gridLayout_3.addWidget(self.treeWidgetSummary, 1, 0, 1, 1)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.lineEditSearchTreeSummary = QtGui.QLineEdit(self.wizardPage4)
        self.lineEditSearchTreeSummary.setEnabled(True)
        self.lineEditSearchTreeSummary.setObjectName(_fromUtf8("lineEditSearchTreeSummary"))
        self.horizontalLayout_3.addWidget(self.lineEditSearchTreeSummary)
        self.btnExpandAll_Summary = QtGui.QPushButton(self.wizardPage4)
        self.btnExpandAll_Summary.setEnabled(True)
        self.btnExpandAll_Summary.setMinimumSize(QtCore.QSize(53, 0))
        self.btnExpandAll_Summary.setMaximumSize(QtCore.QSize(53, 16777215))
        self.btnExpandAll_Summary.setObjectName(_fromUtf8("btnExpandAll_Summary"))
        self.horizontalLayout_3.addWidget(self.btnExpandAll_Summary)
        self.btnCollapseAll_Summary = QtGui.QPushButton(self.wizardPage4)
        self.btnCollapseAll_Summary.setEnabled(True)
        self.btnCollapseAll_Summary.setMinimumSize(QtCore.QSize(53, 0))
        self.btnCollapseAll_Summary.setMaximumSize(QtCore.QSize(53, 16777215))
        self.btnCollapseAll_Summary.setObjectName(_fromUtf8("btnCollapseAll_Summary"))
        self.horizontalLayout_3.addWidget(self.btnCollapseAll_Summary)
        self.gridLayout_3.addLayout(self.horizontalLayout_3, 2, 0, 1, 1)
        WizardSearchByClassName.addPage(self.wizardPage4)

        self.retranslateUi(WizardSearchByClassName)
        QtCore.QMetaObject.connectSlotsByName(WizardSearchByClassName)

    def retranslateUi(self, WizardSearchByClassName):
        WizardSearchByClassName.setWindowTitle(_translate("WizardSearchByClassName", "Search by Class - Step 1", None))
        self.lblSearchClassInEM.setToolTip(_translate("WizardSearchByClassName", "Define a class to search in External Model, in the form of <prefix:className>", None))
        self.lblSearchClassInEM.setText(_translate("WizardSearchByClassName", "Search for class in External Model", None))
        self.comboBoxNamespaces.setToolTip(_translate("WizardSearchByClassName", "Select a prefix from a pre-defined list. If prefix is not enlisted, please add it manually, through the Preferences window", None))
        self.lineEditSearchClassInEMClassName.setToolTip(_translate("WizardSearchByClassName", "Type the name of the class to search for in External Model", None))
        self.btnSearchClassInEM.setText(_translate("WizardSearchByClassName", "Search", None))
        self.treeWidgetSearchClassInEMInstancesResults.setToolTip(_translate("WizardSearchByClassName", "Instances found in External Model - Please select one or more instances to import to My Model", None))
        self.treeWidgetSearchClassInEMInstancesResults.setWhatsThis(_translate("WizardSearchByClassName", "Instances found in external model - Please select one or more Instances to import to my model", None))
        self.treeWidgetSearchClassInEMInstancesResults.headerItem().setText(0, _translate("WizardSearchByClassName", "Instances", None))
        self.treeWidgetSearchClassInEMInstancesResults.headerItem().setText(1, _translate("WizardSearchByClassName", "Values", None))
        self.btnAllPage1.setToolTip(_translate("WizardSearchByClassName", "Select all", None))
        self.btnAllPage1.setText(_translate("WizardSearchByClassName", "All", None))
        self.btnNonePage1.setToolTip(_translate("WizardSearchByClassName", "Select none", None))
        self.btnNonePage1.setText(_translate("WizardSearchByClassName", "None", None))
        self.lineEditSearchTreePage1.setPlaceholderText(_translate("WizardSearchByClassName", "Search tree...", None))
        self.btnExpandAll.setText(_translate("WizardSearchByClassName", "Expand", None))
        self.btnCollapseAll.setText(_translate("WizardSearchByClassName", "Collapse", None))
        self.lblSearching.setText(_translate("WizardSearchByClassName", "Searching...", None))
        self.comboBoxAvailableClassesInMM.setToolTip(_translate("WizardSearchByClassName", "Select a class from My Model where selected instances will be imported", None))
        self.comboBoxAvailableClassesInMM.setWhatsThis(_translate("WizardSearchByClassName", "Select a class of my model to import new instances", None))
        self.lblPromptMessageInSearchClassInMM.setText(_translate("WizardSearchByClassName", "lbl", None))
        self.lblShowPropertiesOfBothModels.setText(_translate("WizardSearchByClassName", "Match properties of <span style=\'font-size:9pt; font-weight:600; color:#000000;\'>External Model</span> to equivalent properties of <span style=\'font-size:9pt; font-weight:600; color:#000000;\'>My Model</span>:", None))
        self.tableWidgetViewPropertiesOfBothModels.setToolTip(_translate("WizardSearchByClassName", "Property Mapping table - Please match My Model properties to External Model properties", None))
        self.tableWidgetViewPropertiesOfBothModels.setWhatsThis(_translate("WizardSearchByClassName", "Property mapping - Please match my model properties to external model properties", None))
        item = self.tableWidgetViewPropertiesOfBothModels.horizontalHeaderItem(0)
        item.setText(_translate("WizardSearchByClassName", "Properties of External Model", None))
        item = self.tableWidgetViewPropertiesOfBothModels.horizontalHeaderItem(1)
        item.setText(_translate("WizardSearchByClassName", "Properties of My Model", None))
        self.lblPopulatedInstances.setText(_translate("WizardSearchByClassName", "TextLabel", None))
        self.treeWidgetSummary.setWhatsThis(_translate("WizardSearchByClassName", "Instances and properties found in external model - Please select the desired properties", None))
        self.treeWidgetSummary.headerItem().setText(0, _translate("WizardSearchByClassName", "Instances", None))
        self.treeWidgetSummary.headerItem().setText(1, _translate("WizardSearchByClassName", "Values", None))
        self.lineEditSearchTreeSummary.setPlaceholderText(_translate("WizardSearchByClassName", "Search tree...", None))
        self.btnExpandAll_Summary.setText(_translate("WizardSearchByClassName", "Expand", None))
        self.btnCollapseAll_Summary.setText(_translate("WizardSearchByClassName", "Collapse", None))

import search_by_class_wizard_resources_rc
