# -*- coding: utf-8 -*-

"""
This file is part of the PROPheT tool.

Copyright (C) 2016: MKLab <pmitzias@iti.gr; mriga@iti.gr; skontopo@iti.gr>

http://mklab.iti.gr/project/prophet-ontology-populator
https://github.com/MKLab-ITI/prophet

Licensed under the Apache License, Version 2.0 (the "License").
You may use this file in compliance with the License. 
For more details, see LICENCE file. 

"""

# Form implementation generated from reading ui file 'ui\EnrichInstanceWizard.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_WizardEnrichInstance(object):
    def setupUi(self, WizardEnrichInstance):
        WizardEnrichInstance.setObjectName(_fromUtf8("WizardEnrichInstance"))
        WizardEnrichInstance.resize(684, 513)
        WizardEnrichInstance.setFocusPolicy(QtCore.Qt.TabFocus)
        WizardEnrichInstance.setContextMenuPolicy(QtCore.Qt.CustomContextMenu)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8(":/images/enirch_instance.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        WizardEnrichInstance.setWindowIcon(icon)
        WizardEnrichInstance.setWizardStyle(QtGui.QWizard.ClassicStyle)
        WizardEnrichInstance.setOptions(QtGui.QWizard.NoCancelButton)
        self.wizardPage1 = QtGui.QWizardPage()
        self.wizardPage1.setTitle(_fromUtf8(""))
        self.wizardPage1.setObjectName(_fromUtf8("wizardPage1"))
        self.gridLayout = QtGui.QGridLayout(self.wizardPage1)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.lblSearchInstanceInEM = QtGui.QLabel(self.wizardPage1)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lblSearchInstanceInEM.setFont(font)
        self.lblSearchInstanceInEM.setWordWrap(True)
        self.lblSearchInstanceInEM.setObjectName(_fromUtf8("lblSearchInstanceInEM"))
        self.gridLayout.addWidget(self.lblSearchInstanceInEM, 0, 0, 1, 1)
        self.treeWidgetSelectInstanceToSearchFor = QtGui.QTreeWidget(self.wizardPage1)
        self.treeWidgetSelectInstanceToSearchFor.setContextMenuPolicy(QtCore.Qt.CustomContextMenu)
        self.treeWidgetSelectInstanceToSearchFor.setAlternatingRowColors(True)
        self.treeWidgetSelectInstanceToSearchFor.setSelectionMode(QtGui.QAbstractItemView.SingleSelection)
        self.treeWidgetSelectInstanceToSearchFor.setSelectionBehavior(QtGui.QAbstractItemView.SelectRows)
        self.treeWidgetSelectInstanceToSearchFor.setObjectName(_fromUtf8("treeWidgetSelectInstanceToSearchFor"))
        self.treeWidgetSelectInstanceToSearchFor.header().setVisible(False)
        self.gridLayout.addWidget(self.treeWidgetSelectInstanceToSearchFor, 1, 0, 1, 1)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.lineEditSearchTreePage1 = QtGui.QLineEdit(self.wizardPage1)
        self.lineEditSearchTreePage1.setEnabled(True)
        self.lineEditSearchTreePage1.setObjectName(_fromUtf8("lineEditSearchTreePage1"))
        self.horizontalLayout.addWidget(self.lineEditSearchTreePage1)
        self.btnExpandAllPage1 = QtGui.QPushButton(self.wizardPage1)
        self.btnExpandAllPage1.setEnabled(True)
        self.btnExpandAllPage1.setMinimumSize(QtCore.QSize(53, 0))
        self.btnExpandAllPage1.setMaximumSize(QtCore.QSize(53, 16777215))
        self.btnExpandAllPage1.setObjectName(_fromUtf8("btnExpandAllPage1"))
        self.horizontalLayout.addWidget(self.btnExpandAllPage1)
        self.btnCollapseAllPage1 = QtGui.QPushButton(self.wizardPage1)
        self.btnCollapseAllPage1.setEnabled(True)
        self.btnCollapseAllPage1.setMinimumSize(QtCore.QSize(53, 0))
        self.btnCollapseAllPage1.setMaximumSize(QtCore.QSize(53, 16777215))
        self.btnCollapseAllPage1.setObjectName(_fromUtf8("btnCollapseAllPage1"))
        self.horizontalLayout.addWidget(self.btnCollapseAllPage1)
        self.gridLayout.addLayout(self.horizontalLayout, 2, 0, 1, 1)
        WizardEnrichInstance.addPage(self.wizardPage1)
        self.wizardPage2 = QtGui.QWizardPage()
        self.wizardPage2.setTitle(_fromUtf8(""))
        self.wizardPage2.setObjectName(_fromUtf8("wizardPage2"))
        self.gridLayout_2 = QtGui.QGridLayout(self.wizardPage2)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.lblSearchForInstanceSimilarInstancesFound = QtGui.QLabel(self.wizardPage2)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lblSearchForInstanceSimilarInstancesFound.setFont(font)
        self.lblSearchForInstanceSimilarInstancesFound.setWordWrap(True)
        self.lblSearchForInstanceSimilarInstancesFound.setObjectName(_fromUtf8("lblSearchForInstanceSimilarInstancesFound"))
        self.gridLayout_2.addWidget(self.lblSearchForInstanceSimilarInstancesFound, 0, 0, 1, 1)
        self.treeWidgetSelectPropertiesToImport = QtGui.QTreeWidget(self.wizardPage2)
        self.treeWidgetSelectPropertiesToImport.setContextMenuPolicy(QtCore.Qt.CustomContextMenu)
        self.treeWidgetSelectPropertiesToImport.setAlternatingRowColors(True)
        self.treeWidgetSelectPropertiesToImport.setSelectionMode(QtGui.QAbstractItemView.ExtendedSelection)
        self.treeWidgetSelectPropertiesToImport.setSelectionBehavior(QtGui.QAbstractItemView.SelectRows)
        self.treeWidgetSelectPropertiesToImport.setObjectName(_fromUtf8("treeWidgetSelectPropertiesToImport"))
        self.treeWidgetSelectPropertiesToImport.header().setVisible(False)
        self.gridLayout_2.addWidget(self.treeWidgetSelectPropertiesToImport, 1, 0, 1, 1)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.btnAllPage2 = QtGui.QPushButton(self.wizardPage2)
        self.btnAllPage2.setMaximumSize(QtCore.QSize(35, 16777215))
        self.btnAllPage2.setFlat(False)
        self.btnAllPage2.setObjectName(_fromUtf8("btnAllPage2"))
        self.horizontalLayout_2.addWidget(self.btnAllPage2)
        self.btnNonePage2 = QtGui.QPushButton(self.wizardPage2)
        self.btnNonePage2.setMaximumSize(QtCore.QSize(35, 16777215))
        self.btnNonePage2.setObjectName(_fromUtf8("btnNonePage2"))
        self.horizontalLayout_2.addWidget(self.btnNonePage2)
        self.lineEditSearchTreePage2 = QtGui.QLineEdit(self.wizardPage2)
        self.lineEditSearchTreePage2.setEnabled(True)
        self.lineEditSearchTreePage2.setObjectName(_fromUtf8("lineEditSearchTreePage2"))
        self.horizontalLayout_2.addWidget(self.lineEditSearchTreePage2)
        self.btnExpandAllPage2 = QtGui.QPushButton(self.wizardPage2)
        self.btnExpandAllPage2.setEnabled(True)
        self.btnExpandAllPage2.setMinimumSize(QtCore.QSize(53, 0))
        self.btnExpandAllPage2.setMaximumSize(QtCore.QSize(53, 16777215))
        self.btnExpandAllPage2.setObjectName(_fromUtf8("btnExpandAllPage2"))
        self.horizontalLayout_2.addWidget(self.btnExpandAllPage2)
        self.btnCollapseAllPage2 = QtGui.QPushButton(self.wizardPage2)
        self.btnCollapseAllPage2.setEnabled(True)
        self.btnCollapseAllPage2.setMinimumSize(QtCore.QSize(53, 0))
        self.btnCollapseAllPage2.setMaximumSize(QtCore.QSize(53, 16777215))
        self.btnCollapseAllPage2.setObjectName(_fromUtf8("btnCollapseAllPage2"))
        self.horizontalLayout_2.addWidget(self.btnCollapseAllPage2)
        self.gridLayout_2.addLayout(self.horizontalLayout_2, 2, 0, 1, 1)
        WizardEnrichInstance.addPage(self.wizardPage2)
        self.wizardPage3 = QtGui.QWizardPage()
        self.wizardPage3.setObjectName(_fromUtf8("wizardPage3"))
        self.gridLayout_4 = QtGui.QGridLayout(self.wizardPage3)
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.lblShowPropertiesOfBothModels = QtGui.QLabel(self.wizardPage3)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lblShowPropertiesOfBothModels.setFont(font)
        self.lblShowPropertiesOfBothModels.setWordWrap(True)
        self.lblShowPropertiesOfBothModels.setObjectName(_fromUtf8("lblShowPropertiesOfBothModels"))
        self.gridLayout_4.addWidget(self.lblShowPropertiesOfBothModels, 0, 0, 1, 1)
        self.tableWidgetViewPropertiesOfBothModels = QtGui.QTableWidget(self.wizardPage3)
        self.tableWidgetViewPropertiesOfBothModels.setAutoFillBackground(False)
        self.tableWidgetViewPropertiesOfBothModels.setEditTriggers(QtGui.QAbstractItemView.NoEditTriggers)
        self.tableWidgetViewPropertiesOfBothModels.setAlternatingRowColors(True)
        self.tableWidgetViewPropertiesOfBothModels.setSelectionMode(QtGui.QAbstractItemView.NoSelection)
        self.tableWidgetViewPropertiesOfBothModels.setObjectName(_fromUtf8("tableWidgetViewPropertiesOfBothModels"))
        self.tableWidgetViewPropertiesOfBothModels.setColumnCount(2)
        self.tableWidgetViewPropertiesOfBothModels.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.tableWidgetViewPropertiesOfBothModels.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidgetViewPropertiesOfBothModels.setHorizontalHeaderItem(1, item)
        self.tableWidgetViewPropertiesOfBothModels.horizontalHeader().setCascadingSectionResizes(False)
        self.tableWidgetViewPropertiesOfBothModels.horizontalHeader().setDefaultSectionSize(300)
        self.tableWidgetViewPropertiesOfBothModels.horizontalHeader().setMinimumSectionSize(300)
        self.tableWidgetViewPropertiesOfBothModels.horizontalHeader().setStretchLastSection(True)
        self.gridLayout_4.addWidget(self.tableWidgetViewPropertiesOfBothModels, 1, 0, 1, 1)
        WizardEnrichInstance.addPage(self.wizardPage3)
        self.wizardPage4 = QtGui.QWizardPage()
        self.wizardPage4.setEnabled(True)
        self.wizardPage4.setTitle(_fromUtf8(""))
        self.wizardPage4.setObjectName(_fromUtf8("wizardPage4"))
        self.gridLayout_3 = QtGui.QGridLayout(self.wizardPage4)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.lblPopulatedInstances = QtGui.QLabel(self.wizardPage4)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lblPopulatedInstances.setFont(font)
        self.lblPopulatedInstances.setObjectName(_fromUtf8("lblPopulatedInstances"))
        self.gridLayout_3.addWidget(self.lblPopulatedInstances, 0, 0, 1, 1)
        self.treeWidgetSummary = QtGui.QTreeWidget(self.wizardPage4)
        self.treeWidgetSummary.setContextMenuPolicy(QtCore.Qt.CustomContextMenu)
        self.treeWidgetSummary.setAlternatingRowColors(True)
        self.treeWidgetSummary.setSelectionMode(QtGui.QAbstractItemView.NoSelection)
        self.treeWidgetSummary.setSelectionBehavior(QtGui.QAbstractItemView.SelectRows)
        self.treeWidgetSummary.setObjectName(_fromUtf8("treeWidgetSummary"))
        self.treeWidgetSummary.header().setVisible(False)
        self.gridLayout_3.addWidget(self.treeWidgetSummary, 1, 0, 1, 1)
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.lineEditSearchTreeSummary = QtGui.QLineEdit(self.wizardPage4)
        self.lineEditSearchTreeSummary.setEnabled(True)
        self.lineEditSearchTreeSummary.setObjectName(_fromUtf8("lineEditSearchTreeSummary"))
        self.horizontalLayout_5.addWidget(self.lineEditSearchTreeSummary)
        self.btnExpandAll_Summary = QtGui.QPushButton(self.wizardPage4)
        self.btnExpandAll_Summary.setEnabled(True)
        self.btnExpandAll_Summary.setMinimumSize(QtCore.QSize(53, 0))
        self.btnExpandAll_Summary.setMaximumSize(QtCore.QSize(53, 16777215))
        self.btnExpandAll_Summary.setObjectName(_fromUtf8("btnExpandAll_Summary"))
        self.horizontalLayout_5.addWidget(self.btnExpandAll_Summary)
        self.btnCollapseAll_Summary = QtGui.QPushButton(self.wizardPage4)
        self.btnCollapseAll_Summary.setEnabled(True)
        self.btnCollapseAll_Summary.setMinimumSize(QtCore.QSize(53, 0))
        self.btnCollapseAll_Summary.setMaximumSize(QtCore.QSize(53, 16777215))
        self.btnCollapseAll_Summary.setObjectName(_fromUtf8("btnCollapseAll_Summary"))
        self.horizontalLayout_5.addWidget(self.btnCollapseAll_Summary)
        self.gridLayout_3.addLayout(self.horizontalLayout_5, 2, 0, 1, 1)
        WizardEnrichInstance.addPage(self.wizardPage4)

        self.retranslateUi(WizardEnrichInstance)
        QtCore.QMetaObject.connectSlotsByName(WizardEnrichInstance)

    def retranslateUi(self, WizardEnrichInstance):
        WizardEnrichInstance.setWindowTitle(_translate("WizardEnrichInstance", "Enrich Instance with Properties - Step 1", None))
        self.lblSearchInstanceInEM.setText(_translate("WizardEnrichInstance", "Select an instance of My Model to search for similar instances in the External Model:", None))
        self.treeWidgetSelectInstanceToSearchFor.setWhatsThis(_translate("WizardEnrichInstance", "Instances in my model - Please select an instance", None))
        self.treeWidgetSelectInstanceToSearchFor.headerItem().setText(0, _translate("WizardEnrichInstance", "Instances", None))
        self.treeWidgetSelectInstanceToSearchFor.headerItem().setText(1, _translate("WizardEnrichInstance", "Values", None))
        self.lineEditSearchTreePage1.setPlaceholderText(_translate("WizardEnrichInstance", "Search tree...", None))
        self.btnExpandAllPage1.setText(_translate("WizardEnrichInstance", "Expand", None))
        self.btnCollapseAllPage1.setText(_translate("WizardEnrichInstance", "Collapse", None))
        self.lblSearchForInstanceSimilarInstancesFound.setText(_translate("WizardEnrichInstance", "Select properties to insert to My Model", None))
        self.treeWidgetSelectPropertiesToImport.setWhatsThis(_translate("WizardEnrichInstance", "Instances and properties found in external model - Please select the desired properties", None))
        self.treeWidgetSelectPropertiesToImport.headerItem().setText(0, _translate("WizardEnrichInstance", "Instances", None))
        self.treeWidgetSelectPropertiesToImport.headerItem().setText(1, _translate("WizardEnrichInstance", "Values", None))
        self.btnAllPage2.setToolTip(_translate("WizardEnrichInstance", "Select all", None))
        self.btnAllPage2.setText(_translate("WizardEnrichInstance", "All", None))
        self.btnNonePage2.setToolTip(_translate("WizardEnrichInstance", "Select none", None))
        self.btnNonePage2.setText(_translate("WizardEnrichInstance", "None", None))
        self.lineEditSearchTreePage2.setPlaceholderText(_translate("WizardEnrichInstance", "Search tree...", None))
        self.btnExpandAllPage2.setText(_translate("WizardEnrichInstance", "Expand", None))
        self.btnCollapseAllPage2.setText(_translate("WizardEnrichInstance", "Collapse", None))
        self.lblShowPropertiesOfBothModels.setText(_translate("WizardEnrichInstance", "Match properties of External Model to My Model", None))
        self.tableWidgetViewPropertiesOfBothModels.setToolTip(_translate("WizardEnrichInstance", "Property Mapping table - Please match My Model properties to External Model properties", None))
        self.tableWidgetViewPropertiesOfBothModels.setWhatsThis(_translate("WizardEnrichInstance", "Property mapping - Please match my model properties to external model properties", None))
        item = self.tableWidgetViewPropertiesOfBothModels.horizontalHeaderItem(0)
        item.setText(_translate("WizardEnrichInstance", "Properties of External Model", None))
        item = self.tableWidgetViewPropertiesOfBothModels.horizontalHeaderItem(1)
        item.setText(_translate("WizardEnrichInstance", "Properties of My Model", None))
        self.lblPopulatedInstances.setText(_translate("WizardEnrichInstance", "TextLabel", None))
        self.treeWidgetSummary.setWhatsThis(_translate("WizardEnrichInstance", "Instances and properties found in external model - Please select the desired properties", None))
        self.treeWidgetSummary.headerItem().setText(0, _translate("WizardEnrichInstance", "Instances", None))
        self.treeWidgetSummary.headerItem().setText(1, _translate("WizardEnrichInstance", "Values", None))
        self.lineEditSearchTreeSummary.setPlaceholderText(_translate("WizardEnrichInstance", "Search tree...", None))
        self.btnExpandAll_Summary.setText(_translate("WizardEnrichInstance", "Expand", None))
        self.btnCollapseAll_Summary.setText(_translate("WizardEnrichInstance", "Collapse", None))

import enrich_instance_wizard_resources_rc
