# -*- coding: utf-8 -*-

"""
This file is part of the PROPheT tool.

Copyright (C) 2016: MKLab <pmitzias@iti.gr; mriga@iti.gr; skontopo@iti.gr>

http://mklab.iti.gr/project/prophet-ontology-populator
https://github.com/MKLab-ITI/prophet

Licensed under the Apache License, Version 2.0 (the "License").
You may use this file in compliance with the License. 
For more details, see LICENCE file. 

"""

# Form implementation generated from reading ui file 'ui\SearchByInstanceWizard.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_WizardSearchByInstanceName(object):
    def setupUi(self, WizardSearchByInstanceName):
        WizardSearchByInstanceName.setObjectName(_fromUtf8("WizardSearchByInstanceName"))
        WizardSearchByInstanceName.resize(684, 513)
        WizardSearchByInstanceName.setFocusPolicy(QtCore.Qt.TabFocus)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8(":/images/search_by_existing_instance.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        WizardSearchByInstanceName.setWindowIcon(icon)
        WizardSearchByInstanceName.setWizardStyle(QtGui.QWizard.ClassicStyle)
        WizardSearchByInstanceName.setOptions(QtGui.QWizard.NoCancelButton)
        self.wizardPage1 = QtGui.QWizardPage()
        self.wizardPage1.setTitle(_fromUtf8(""))
        self.wizardPage1.setObjectName(_fromUtf8("wizardPage1"))
        self.gridLayout = QtGui.QGridLayout(self.wizardPage1)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.lblSearchInstanceInEM = QtGui.QLabel(self.wizardPage1)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lblSearchInstanceInEM.setFont(font)
        self.lblSearchInstanceInEM.setWordWrap(True)
        self.lblSearchInstanceInEM.setObjectName(_fromUtf8("lblSearchInstanceInEM"))
        self.gridLayout.addWidget(self.lblSearchInstanceInEM, 0, 0, 1, 1)
        self.treeWidgetSelectInstanceToSearchFor = QtGui.QTreeWidget(self.wizardPage1)
        self.treeWidgetSelectInstanceToSearchFor.setContextMenuPolicy(QtCore.Qt.CustomContextMenu)
        self.treeWidgetSelectInstanceToSearchFor.setAlternatingRowColors(True)
        self.treeWidgetSelectInstanceToSearchFor.setSelectionMode(QtGui.QAbstractItemView.SingleSelection)
        self.treeWidgetSelectInstanceToSearchFor.setSelectionBehavior(QtGui.QAbstractItemView.SelectRows)
        self.treeWidgetSelectInstanceToSearchFor.setObjectName(_fromUtf8("treeWidgetSelectInstanceToSearchFor"))
        self.treeWidgetSelectInstanceToSearchFor.header().setVisible(False)
        self.gridLayout.addWidget(self.treeWidgetSelectInstanceToSearchFor, 1, 0, 1, 1)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.lineEditSearchTreePage1 = QtGui.QLineEdit(self.wizardPage1)
        self.lineEditSearchTreePage1.setEnabled(True)
        self.lineEditSearchTreePage1.setObjectName(_fromUtf8("lineEditSearchTreePage1"))
        self.horizontalLayout_3.addWidget(self.lineEditSearchTreePage1)
        self.btnExpandAll_page1 = QtGui.QPushButton(self.wizardPage1)
        self.btnExpandAll_page1.setEnabled(True)
        self.btnExpandAll_page1.setMinimumSize(QtCore.QSize(53, 0))
        self.btnExpandAll_page1.setMaximumSize(QtCore.QSize(53, 16777215))
        self.btnExpandAll_page1.setObjectName(_fromUtf8("btnExpandAll_page1"))
        self.horizontalLayout_3.addWidget(self.btnExpandAll_page1)
        self.btnCollapseAll_page1 = QtGui.QPushButton(self.wizardPage1)
        self.btnCollapseAll_page1.setEnabled(True)
        self.btnCollapseAll_page1.setMinimumSize(QtCore.QSize(53, 0))
        self.btnCollapseAll_page1.setMaximumSize(QtCore.QSize(53, 16777215))
        self.btnCollapseAll_page1.setObjectName(_fromUtf8("btnCollapseAll_page1"))
        self.horizontalLayout_3.addWidget(self.btnCollapseAll_page1)
        self.gridLayout.addLayout(self.horizontalLayout_3, 2, 0, 1, 1)
        WizardSearchByInstanceName.addPage(self.wizardPage1)
        self.wizardPage2 = QtGui.QWizardPage()
        self.wizardPage2.setTitle(_fromUtf8(""))
        self.wizardPage2.setObjectName(_fromUtf8("wizardPage2"))
        self.gridLayout_2 = QtGui.QGridLayout(self.wizardPage2)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.lblSearchForInstanceClassesFound = QtGui.QLabel(self.wizardPage2)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lblSearchForInstanceClassesFound.setFont(font)
        self.lblSearchForInstanceClassesFound.setWordWrap(True)
        self.lblSearchForInstanceClassesFound.setObjectName(_fromUtf8("lblSearchForInstanceClassesFound"))
        self.gridLayout_2.addWidget(self.lblSearchForInstanceClassesFound, 0, 0, 1, 1)
        self.treeWidgetSelectClasses = QtGui.QTreeWidget(self.wizardPage2)
        self.treeWidgetSelectClasses.setContextMenuPolicy(QtCore.Qt.CustomContextMenu)
        self.treeWidgetSelectClasses.setAlternatingRowColors(True)
        self.treeWidgetSelectClasses.setSelectionMode(QtGui.QAbstractItemView.ExtendedSelection)
        self.treeWidgetSelectClasses.setSelectionBehavior(QtGui.QAbstractItemView.SelectRows)
        self.treeWidgetSelectClasses.setObjectName(_fromUtf8("treeWidgetSelectClasses"))
        self.treeWidgetSelectClasses.header().setVisible(False)
        self.gridLayout_2.addWidget(self.treeWidgetSelectClasses, 1, 0, 1, 1)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.btnAllPage2 = QtGui.QPushButton(self.wizardPage2)
        self.btnAllPage2.setMaximumSize(QtCore.QSize(35, 16777215))
        self.btnAllPage2.setFlat(False)
        self.btnAllPage2.setObjectName(_fromUtf8("btnAllPage2"))
        self.horizontalLayout.addWidget(self.btnAllPage2)
        self.btnNonePage2 = QtGui.QPushButton(self.wizardPage2)
        self.btnNonePage2.setMaximumSize(QtCore.QSize(35, 16777215))
        self.btnNonePage2.setObjectName(_fromUtf8("btnNonePage2"))
        self.horizontalLayout.addWidget(self.btnNonePage2)
        self.lineEditSearchTreePage2 = QtGui.QLineEdit(self.wizardPage2)
        self.lineEditSearchTreePage2.setEnabled(False)
        self.lineEditSearchTreePage2.setObjectName(_fromUtf8("lineEditSearchTreePage2"))
        self.horizontalLayout.addWidget(self.lineEditSearchTreePage2)
        self.gridLayout_2.addLayout(self.horizontalLayout, 2, 0, 1, 1)
        WizardSearchByInstanceName.addPage(self.wizardPage2)
        self.wizardPage3 = QtGui.QWizardPage()
        self.wizardPage3.setObjectName(_fromUtf8("wizardPage3"))
        self.gridLayout_6 = QtGui.QGridLayout(self.wizardPage3)
        self.gridLayout_6.setObjectName(_fromUtf8("gridLayout_6"))
        self.lblSearchForInstanceInstancesFound = QtGui.QLabel(self.wizardPage3)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lblSearchForInstanceInstancesFound.setFont(font)
        self.lblSearchForInstanceInstancesFound.setWordWrap(True)
        self.lblSearchForInstanceInstancesFound.setObjectName(_fromUtf8("lblSearchForInstanceInstancesFound"))
        self.gridLayout_6.addWidget(self.lblSearchForInstanceInstancesFound, 0, 0, 1, 1)
        self.treeWidgetSelectInstancesToImport = QtGui.QTreeWidget(self.wizardPage3)
        self.treeWidgetSelectInstancesToImport.setContextMenuPolicy(QtCore.Qt.CustomContextMenu)
        self.treeWidgetSelectInstancesToImport.setAlternatingRowColors(True)
        self.treeWidgetSelectInstancesToImport.setSelectionMode(QtGui.QAbstractItemView.ExtendedSelection)
        self.treeWidgetSelectInstancesToImport.setSelectionBehavior(QtGui.QAbstractItemView.SelectRows)
        self.treeWidgetSelectInstancesToImport.setObjectName(_fromUtf8("treeWidgetSelectInstancesToImport"))
        self.treeWidgetSelectInstancesToImport.header().setVisible(False)
        self.gridLayout_6.addWidget(self.treeWidgetSelectInstancesToImport, 1, 0, 1, 1)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.btnAllPage3 = QtGui.QPushButton(self.wizardPage3)
        self.btnAllPage3.setMaximumSize(QtCore.QSize(35, 16777215))
        self.btnAllPage3.setFlat(False)
        self.btnAllPage3.setObjectName(_fromUtf8("btnAllPage3"))
        self.horizontalLayout_2.addWidget(self.btnAllPage3)
        self.btnNonePage3 = QtGui.QPushButton(self.wizardPage3)
        self.btnNonePage3.setMaximumSize(QtCore.QSize(35, 16777215))
        self.btnNonePage3.setObjectName(_fromUtf8("btnNonePage3"))
        self.horizontalLayout_2.addWidget(self.btnNonePage3)
        self.lineEditSearchTreePage3 = QtGui.QLineEdit(self.wizardPage3)
        self.lineEditSearchTreePage3.setEnabled(True)
        self.lineEditSearchTreePage3.setObjectName(_fromUtf8("lineEditSearchTreePage3"))
        self.horizontalLayout_2.addWidget(self.lineEditSearchTreePage3)
        self.btnExpandAll_page3 = QtGui.QPushButton(self.wizardPage3)
        self.btnExpandAll_page3.setEnabled(True)
        self.btnExpandAll_page3.setMinimumSize(QtCore.QSize(53, 0))
        self.btnExpandAll_page3.setMaximumSize(QtCore.QSize(53, 16777215))
        self.btnExpandAll_page3.setObjectName(_fromUtf8("btnExpandAll_page3"))
        self.horizontalLayout_2.addWidget(self.btnExpandAll_page3)
        self.btnCollapseAll_page3 = QtGui.QPushButton(self.wizardPage3)
        self.btnCollapseAll_page3.setEnabled(True)
        self.btnCollapseAll_page3.setMinimumSize(QtCore.QSize(53, 0))
        self.btnCollapseAll_page3.setMaximumSize(QtCore.QSize(53, 16777215))
        self.btnCollapseAll_page3.setObjectName(_fromUtf8("btnCollapseAll_page3"))
        self.horizontalLayout_2.addWidget(self.btnCollapseAll_page3)
        self.gridLayout_6.addLayout(self.horizontalLayout_2, 2, 0, 1, 1)
        WizardSearchByInstanceName.addPage(self.wizardPage3)
        self.wizardPage4 = QtGui.QWizardPage()
        self.wizardPage4.setObjectName(_fromUtf8("wizardPage4"))
        self.gridLayout_5 = QtGui.QGridLayout(self.wizardPage4)
        self.gridLayout_5.setObjectName(_fromUtf8("gridLayout_5"))
        self.lblSelectMyModelClassToImportInstances = QtGui.QLabel(self.wizardPage4)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lblSelectMyModelClassToImportInstances.setFont(font)
        self.lblSelectMyModelClassToImportInstances.setObjectName(_fromUtf8("lblSelectMyModelClassToImportInstances"))
        self.gridLayout_5.addWidget(self.lblSelectMyModelClassToImportInstances, 0, 0, 1, 1)
        self.comboBoxMyModelClasses = QtGui.QComboBox(self.wizardPage4)
        self.comboBoxMyModelClasses.setObjectName(_fromUtf8("comboBoxMyModelClasses"))
        self.gridLayout_5.addWidget(self.comboBoxMyModelClasses, 1, 0, 1, 1)
        WizardSearchByInstanceName.addPage(self.wizardPage4)
        self.wizardPage5 = QtGui.QWizardPage()
        self.wizardPage5.setObjectName(_fromUtf8("wizardPage5"))
        self.gridLayout_4 = QtGui.QGridLayout(self.wizardPage5)
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.lblShowPropertiesOfBothModels = QtGui.QLabel(self.wizardPage5)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lblShowPropertiesOfBothModels.setFont(font)
        self.lblShowPropertiesOfBothModels.setWordWrap(True)
        self.lblShowPropertiesOfBothModels.setObjectName(_fromUtf8("lblShowPropertiesOfBothModels"))
        self.gridLayout_4.addWidget(self.lblShowPropertiesOfBothModels, 0, 0, 1, 1)
        self.tableWidgetViewPropertiesOfBothModels = QtGui.QTableWidget(self.wizardPage5)
        self.tableWidgetViewPropertiesOfBothModels.setAutoFillBackground(False)
        self.tableWidgetViewPropertiesOfBothModels.setEditTriggers(QtGui.QAbstractItemView.NoEditTriggers)
        self.tableWidgetViewPropertiesOfBothModels.setAlternatingRowColors(True)
        self.tableWidgetViewPropertiesOfBothModels.setSelectionMode(QtGui.QAbstractItemView.NoSelection)
        self.tableWidgetViewPropertiesOfBothModels.setObjectName(_fromUtf8("tableWidgetViewPropertiesOfBothModels"))
        self.tableWidgetViewPropertiesOfBothModels.setColumnCount(2)
        self.tableWidgetViewPropertiesOfBothModels.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.tableWidgetViewPropertiesOfBothModels.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidgetViewPropertiesOfBothModels.setHorizontalHeaderItem(1, item)
        self.tableWidgetViewPropertiesOfBothModels.horizontalHeader().setCascadingSectionResizes(False)
        self.tableWidgetViewPropertiesOfBothModels.horizontalHeader().setDefaultSectionSize(300)
        self.tableWidgetViewPropertiesOfBothModels.horizontalHeader().setMinimumSectionSize(300)
        self.tableWidgetViewPropertiesOfBothModels.horizontalHeader().setStretchLastSection(True)
        self.gridLayout_4.addWidget(self.tableWidgetViewPropertiesOfBothModels, 1, 0, 1, 1)
        WizardSearchByInstanceName.addPage(self.wizardPage5)
        self.wizardPage6 = QtGui.QWizardPage()
        self.wizardPage6.setEnabled(True)
        self.wizardPage6.setTitle(_fromUtf8(""))
        self.wizardPage6.setObjectName(_fromUtf8("wizardPage6"))
        self.gridLayout_3 = QtGui.QGridLayout(self.wizardPage6)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.lblPopulatedInstances = QtGui.QLabel(self.wizardPage6)
        self.lblPopulatedInstances.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lblPopulatedInstances.setFont(font)
        self.lblPopulatedInstances.setWordWrap(True)
        self.lblPopulatedInstances.setObjectName(_fromUtf8("lblPopulatedInstances"))
        self.gridLayout_3.addWidget(self.lblPopulatedInstances, 0, 0, 1, 1)
        self.treeWidgetSummary = QtGui.QTreeWidget(self.wizardPage6)
        self.treeWidgetSummary.setContextMenuPolicy(QtCore.Qt.CustomContextMenu)
        self.treeWidgetSummary.setAlternatingRowColors(True)
        self.treeWidgetSummary.setSelectionMode(QtGui.QAbstractItemView.NoSelection)
        self.treeWidgetSummary.setSelectionBehavior(QtGui.QAbstractItemView.SelectRows)
        self.treeWidgetSummary.setAllColumnsShowFocus(False)
        self.treeWidgetSummary.setObjectName(_fromUtf8("treeWidgetSummary"))
        self.treeWidgetSummary.header().setVisible(False)
        self.gridLayout_3.addWidget(self.treeWidgetSummary, 1, 0, 1, 1)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.lineEditSearchTreeSummary = QtGui.QLineEdit(self.wizardPage6)
        self.lineEditSearchTreeSummary.setEnabled(True)
        self.lineEditSearchTreeSummary.setObjectName(_fromUtf8("lineEditSearchTreeSummary"))
        self.horizontalLayout_4.addWidget(self.lineEditSearchTreeSummary)
        self.btnExpandAll_Summary = QtGui.QPushButton(self.wizardPage6)
        self.btnExpandAll_Summary.setEnabled(True)
        self.btnExpandAll_Summary.setMinimumSize(QtCore.QSize(53, 0))
        self.btnExpandAll_Summary.setMaximumSize(QtCore.QSize(53, 16777215))
        self.btnExpandAll_Summary.setObjectName(_fromUtf8("btnExpandAll_Summary"))
        self.horizontalLayout_4.addWidget(self.btnExpandAll_Summary)
        self.btnCollapseAll_Summary = QtGui.QPushButton(self.wizardPage6)
        self.btnCollapseAll_Summary.setEnabled(True)
        self.btnCollapseAll_Summary.setMinimumSize(QtCore.QSize(53, 0))
        self.btnCollapseAll_Summary.setMaximumSize(QtCore.QSize(53, 16777215))
        self.btnCollapseAll_Summary.setObjectName(_fromUtf8("btnCollapseAll_Summary"))
        self.horizontalLayout_4.addWidget(self.btnCollapseAll_Summary)
        self.gridLayout_3.addLayout(self.horizontalLayout_4, 2, 0, 1, 1)
        WizardSearchByInstanceName.addPage(self.wizardPage6)

        self.retranslateUi(WizardSearchByInstanceName)
        QtCore.QMetaObject.connectSlotsByName(WizardSearchByInstanceName)

    def retranslateUi(self, WizardSearchByInstanceName):
        WizardSearchByInstanceName.setWindowTitle(_translate("WizardSearchByInstanceName", "Search by Existing Instance - Step 1", None))
        self.lblSearchInstanceInEM.setText(_translate("WizardSearchByInstanceName", "Select an instance of <span style=\'font-size:9pt; font-weight:600; color:#000000;\'>My Model</span> to search for similar instances in the <span style=\'font-size:9pt; font-weight:600; color:#000000;\'>External Model</span>:", None))
        self.treeWidgetSelectInstanceToSearchFor.setToolTip(_translate("WizardSearchByInstanceName", "Instances in My Model - Please select an instance to be used in search process", None))
        self.treeWidgetSelectInstanceToSearchFor.setWhatsThis(_translate("WizardSearchByInstanceName", "Instances in my model - Please select an instance", None))
        self.treeWidgetSelectInstanceToSearchFor.headerItem().setText(0, _translate("WizardSearchByInstanceName", "Instances", None))
        self.treeWidgetSelectInstanceToSearchFor.headerItem().setText(1, _translate("WizardSearchByInstanceName", "Values", None))
        self.lineEditSearchTreePage1.setPlaceholderText(_translate("WizardSearchByInstanceName", "Search tree...", None))
        self.btnExpandAll_page1.setText(_translate("WizardSearchByInstanceName", "Expand", None))
        self.btnCollapseAll_page1.setText(_translate("WizardSearchByInstanceName", "Collapse", None))
        self.lblSearchForInstanceClassesFound.setText(_translate("WizardSearchByInstanceName", "Class found.", None))
        self.treeWidgetSelectClasses.setToolTip(_translate("WizardSearchByInstanceName", "Classes found in External Model - Please select one or more classes to search for its/their instances in External Model", None))
        self.treeWidgetSelectClasses.setWhatsThis(_translate("WizardSearchByInstanceName", "External model classes - Please select a class or more to search for instances", None))
        self.treeWidgetSelectClasses.headerItem().setText(0, _translate("WizardSearchByInstanceName", "Instances", None))
        self.btnAllPage2.setToolTip(_translate("WizardSearchByInstanceName", "Select all", None))
        self.btnAllPage2.setText(_translate("WizardSearchByInstanceName", "All", None))
        self.btnNonePage2.setToolTip(_translate("WizardSearchByInstanceName", "Select none", None))
        self.btnNonePage2.setText(_translate("WizardSearchByInstanceName", "None", None))
        self.lineEditSearchTreePage2.setPlaceholderText(_translate("WizardSearchByInstanceName", "Search tree...", None))
        self.lblSearchForInstanceInstancesFound.setText(_translate("WizardSearchByInstanceName", "Selected classes and their instances.", None))
        self.treeWidgetSelectInstancesToImport.setToolTip(_translate("WizardSearchByInstanceName", "Instances of selected classes found in External Model - Please select one or more instances to import to My Model", None))
        self.treeWidgetSelectInstancesToImport.setWhatsThis(_translate("WizardSearchByInstanceName", "Instances in selected classes - Please select an instance or more to import to my model", None))
        self.treeWidgetSelectInstancesToImport.headerItem().setText(0, _translate("WizardSearchByInstanceName", "Instances", None))
        self.treeWidgetSelectInstancesToImport.headerItem().setText(1, _translate("WizardSearchByInstanceName", "Values", None))
        self.btnAllPage3.setToolTip(_translate("WizardSearchByInstanceName", "Select all", None))
        self.btnAllPage3.setText(_translate("WizardSearchByInstanceName", "All", None))
        self.btnNonePage3.setToolTip(_translate("WizardSearchByInstanceName", "Select none", None))
        self.btnNonePage3.setText(_translate("WizardSearchByInstanceName", "None", None))
        self.lineEditSearchTreePage3.setPlaceholderText(_translate("WizardSearchByInstanceName", "Search tree...", None))
        self.btnExpandAll_page3.setText(_translate("WizardSearchByInstanceName", "Expand", None))
        self.btnCollapseAll_page3.setText(_translate("WizardSearchByInstanceName", "Collapse", None))
        self.lblSelectMyModelClassToImportInstances.setText(_translate("WizardSearchByInstanceName", "Select a class from <span style=\'font-size:9pt; font-weight:600; color:#000000;\'>My Model</span> to import instances:", None))
        self.comboBoxMyModelClasses.setToolTip(_translate("WizardSearchByInstanceName", "Select a class from My Model where selected instances will be imported", None))
        self.comboBoxMyModelClasses.setWhatsThis(_translate("WizardSearchByInstanceName", "Select a class of my model to import new instances", None))
        self.lblShowPropertiesOfBothModels.setText(_translate("WizardSearchByInstanceName", "Match properties of External Model to My Model", None))
        self.tableWidgetViewPropertiesOfBothModels.setToolTip(_translate("WizardSearchByInstanceName", "Property Mapping table - Please match My Model properties to External Model properties", None))
        self.tableWidgetViewPropertiesOfBothModels.setWhatsThis(_translate("WizardSearchByInstanceName", "Property mapping - Please match my model properties to external model properties", None))
        item = self.tableWidgetViewPropertiesOfBothModels.horizontalHeaderItem(0)
        item.setText(_translate("WizardSearchByInstanceName", "Properties of External Model", None))
        item = self.tableWidgetViewPropertiesOfBothModels.horizontalHeaderItem(1)
        item.setText(_translate("WizardSearchByInstanceName", "Properties of My Model", None))
        self.lblPopulatedInstances.setText(_translate("WizardSearchByInstanceName", "TextLabel", None))
        self.treeWidgetSummary.setWhatsThis(_translate("WizardSearchByInstanceName", "Instances found in external model - Please select one or more Instances to import to my model", None))
        self.treeWidgetSummary.headerItem().setText(0, _translate("WizardSearchByInstanceName", "Instances", None))
        self.treeWidgetSummary.headerItem().setText(1, _translate("WizardSearchByInstanceName", "Value", None))
        self.lineEditSearchTreeSummary.setPlaceholderText(_translate("WizardSearchByInstanceName", "Search tree...", None))
        self.btnExpandAll_Summary.setText(_translate("WizardSearchByInstanceName", "Expand", None))
        self.btnCollapseAll_Summary.setText(_translate("WizardSearchByInstanceName", "Collapse", None))

import search_by_existing_instance_wizard_resources_rc
