# -*- coding: utf-8 -*-

"""
This file is part of the PROPheT tool.

Copyright (C) 2016: MKLab <pmitzias@iti.gr; mriga@iti.gr; skontopo@iti.gr>

http://mklab.iti.gr/project/prophet-ontology-populator
https://github.com/MKLab-ITI/prophet

Licensed under the Apache License, Version 2.0 (the "License").
You may use this file in compliance with the License. 
For more details, see LICENCE file. 

"""

# Form implementation generated from reading ui file 'ui\SearchByInstanceLabelWizard.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_WizardSearchByInstanceLabel(object):
    def setupUi(self, WizardSearchByInstanceLabel):
        WizardSearchByInstanceLabel.setObjectName(_fromUtf8("WizardSearchByInstanceLabel"))
        WizardSearchByInstanceLabel.resize(684, 513)
        WizardSearchByInstanceLabel.setFocusPolicy(QtCore.Qt.TabFocus)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8(":/images/search_by_instance_label.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        WizardSearchByInstanceLabel.setWindowIcon(icon)
        WizardSearchByInstanceLabel.setWizardStyle(QtGui.QWizard.ClassicStyle)
        WizardSearchByInstanceLabel.setOptions(QtGui.QWizard.NoCancelButton)
        self.wizardPage1 = QtGui.QWizardPage()
        self.wizardPage1.setTitle(_fromUtf8(""))
        self.wizardPage1.setObjectName(_fromUtf8("wizardPage1"))
        self.gridLayout_3 = QtGui.QGridLayout(self.wizardPage1)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.lblSearchInstanceLabelInEM = QtGui.QLabel(self.wizardPage1)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lblSearchInstanceLabelInEM.setFont(font)
        self.lblSearchInstanceLabelInEM.setWordWrap(True)
        self.lblSearchInstanceLabelInEM.setObjectName(_fromUtf8("lblSearchInstanceLabelInEM"))
        self.gridLayout_3.addWidget(self.lblSearchInstanceLabelInEM, 0, 0, 1, 1)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.lineEditSearchInstanceLabelInEMClassName = QtGui.QLineEdit(self.wizardPage1)
        self.lineEditSearchInstanceLabelInEMClassName.setObjectName(_fromUtf8("lineEditSearchInstanceLabelInEMClassName"))
        self.horizontalLayout_4.addWidget(self.lineEditSearchInstanceLabelInEMClassName)
        self.btnSearchInstanceLabelInEM = QtGui.QPushButton(self.wizardPage1)
        self.btnSearchInstanceLabelInEM.setEnabled(False)
        self.btnSearchInstanceLabelInEM.setMaximumSize(QtCore.QSize(100, 16777215))
        self.btnSearchInstanceLabelInEM.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.btnSearchInstanceLabelInEM.setAutoDefault(False)
        self.btnSearchInstanceLabelInEM.setDefault(False)
        self.btnSearchInstanceLabelInEM.setObjectName(_fromUtf8("btnSearchInstanceLabelInEM"))
        self.horizontalLayout_4.addWidget(self.btnSearchInstanceLabelInEM)
        self.gridLayout_3.addLayout(self.horizontalLayout_4, 1, 0, 1, 1)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.radioButtonExactMatch = QtGui.QRadioButton(self.wizardPage1)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.radioButtonExactMatch.sizePolicy().hasHeightForWidth())
        self.radioButtonExactMatch.setSizePolicy(sizePolicy)
        self.radioButtonExactMatch.setChecked(True)
        self.radioButtonExactMatch.setObjectName(_fromUtf8("radioButtonExactMatch"))
        self.horizontalLayout.addWidget(self.radioButtonExactMatch)
        self.radioButtonContainsTerm = QtGui.QRadioButton(self.wizardPage1)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.radioButtonContainsTerm.sizePolicy().hasHeightForWidth())
        self.radioButtonContainsTerm.setSizePolicy(sizePolicy)
        self.radioButtonContainsTerm.setObjectName(_fromUtf8("radioButtonContainsTerm"))
        self.horizontalLayout.addWidget(self.radioButtonContainsTerm)
        self.checkBoxCaseSensitive = QtGui.QCheckBox(self.wizardPage1)
        self.checkBoxCaseSensitive.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.checkBoxCaseSensitive.sizePolicy().hasHeightForWidth())
        self.checkBoxCaseSensitive.setSizePolicy(sizePolicy)
        self.checkBoxCaseSensitive.setObjectName(_fromUtf8("checkBoxCaseSensitive"))
        self.horizontalLayout.addWidget(self.checkBoxCaseSensitive)
        self.horizontalLayout_2.addLayout(self.horizontalLayout)
        self.line = QtGui.QFrame(self.wizardPage1)
        self.line.setFrameShape(QtGui.QFrame.VLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName(_fromUtf8("line"))
        self.horizontalLayout_2.addWidget(self.line)
        self.comboBoxSearchLanguage = QtGui.QComboBox(self.wizardPage1)
        self.comboBoxSearchLanguage.setObjectName(_fromUtf8("comboBoxSearchLanguage"))
        self.comboBoxSearchLanguage.addItem(_fromUtf8(""))
        self.comboBoxSearchLanguage.addItem(_fromUtf8(""))
        self.horizontalLayout_2.addWidget(self.comboBoxSearchLanguage)
        spacerItem = QtGui.QSpacerItem(238, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.gridLayout_3.addLayout(self.horizontalLayout_2, 2, 0, 1, 1)
        self.treeWidgetSearchInstanceLabelInEMInstancesResults = QtGui.QTreeWidget(self.wizardPage1)
        self.treeWidgetSearchInstanceLabelInEMInstancesResults.setContextMenuPolicy(QtCore.Qt.CustomContextMenu)
        self.treeWidgetSearchInstanceLabelInEMInstancesResults.setAlternatingRowColors(True)
        self.treeWidgetSearchInstanceLabelInEMInstancesResults.setSelectionMode(QtGui.QAbstractItemView.ExtendedSelection)
        self.treeWidgetSearchInstanceLabelInEMInstancesResults.setSelectionBehavior(QtGui.QAbstractItemView.SelectRows)
        self.treeWidgetSearchInstanceLabelInEMInstancesResults.setAllColumnsShowFocus(False)
        self.treeWidgetSearchInstanceLabelInEMInstancesResults.setObjectName(_fromUtf8("treeWidgetSearchInstanceLabelInEMInstancesResults"))
        self.treeWidgetSearchInstanceLabelInEMInstancesResults.header().setVisible(False)
        self.gridLayout_3.addWidget(self.treeWidgetSearchInstanceLabelInEMInstancesResults, 3, 0, 1, 1)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.btnAllPage1 = QtGui.QPushButton(self.wizardPage1)
        self.btnAllPage1.setEnabled(False)
        self.btnAllPage1.setMaximumSize(QtCore.QSize(35, 16777215))
        self.btnAllPage1.setFlat(False)
        self.btnAllPage1.setObjectName(_fromUtf8("btnAllPage1"))
        self.horizontalLayout_3.addWidget(self.btnAllPage1)
        self.btnNonePage1 = QtGui.QPushButton(self.wizardPage1)
        self.btnNonePage1.setEnabled(False)
        self.btnNonePage1.setMaximumSize(QtCore.QSize(35, 16777215))
        self.btnNonePage1.setObjectName(_fromUtf8("btnNonePage1"))
        self.horizontalLayout_3.addWidget(self.btnNonePage1)
        self.lineEditSearchTreePage1 = QtGui.QLineEdit(self.wizardPage1)
        self.lineEditSearchTreePage1.setEnabled(False)
        self.lineEditSearchTreePage1.setObjectName(_fromUtf8("lineEditSearchTreePage1"))
        self.horizontalLayout_3.addWidget(self.lineEditSearchTreePage1)
        self.btnExpandAll = QtGui.QPushButton(self.wizardPage1)
        self.btnExpandAll.setEnabled(False)
        self.btnExpandAll.setMinimumSize(QtCore.QSize(53, 0))
        self.btnExpandAll.setMaximumSize(QtCore.QSize(53, 16777215))
        self.btnExpandAll.setObjectName(_fromUtf8("btnExpandAll"))
        self.horizontalLayout_3.addWidget(self.btnExpandAll)
        self.btnCollapseAll = QtGui.QPushButton(self.wizardPage1)
        self.btnCollapseAll.setEnabled(False)
        self.btnCollapseAll.setMinimumSize(QtCore.QSize(53, 0))
        self.btnCollapseAll.setMaximumSize(QtCore.QSize(53, 16777215))
        self.btnCollapseAll.setObjectName(_fromUtf8("btnCollapseAll"))
        self.horizontalLayout_3.addWidget(self.btnCollapseAll)
        self.lblSearching = QtGui.QLabel(self.wizardPage1)
        self.lblSearching.setObjectName(_fromUtf8("lblSearching"))
        self.horizontalLayout_3.addWidget(self.lblSearching)
        self.gridLayout_3.addLayout(self.horizontalLayout_3, 4, 0, 1, 1)
        self.treeWidgetSearchInstanceLabelInEMInstancesResults.raise_()
        self.lblSearchInstanceLabelInEM.raise_()
        self.lineEditSearchInstanceLabelInEMClassName.raise_()
        self.btnSearchInstanceLabelInEM.raise_()
        self.lineEditSearchTreePage1.raise_()
        self.btnExpandAll.raise_()
        self.btnCollapseAll.raise_()
        WizardSearchByInstanceLabel.addPage(self.wizardPage1)
        self.wizardPage2 = QtGui.QWizardPage()
        self.wizardPage2.setObjectName(_fromUtf8("wizardPage2"))
        self.gridLayout_4 = QtGui.QGridLayout(self.wizardPage2)
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.comboBoxMyModelClasses = QtGui.QComboBox(self.wizardPage2)
        self.comboBoxMyModelClasses.setObjectName(_fromUtf8("comboBoxMyModelClasses"))
        self.gridLayout_4.addWidget(self.comboBoxMyModelClasses, 1, 0, 1, 3)
        self.lblSelectMyModelClassToImportInstances = QtGui.QLabel(self.wizardPage2)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lblSelectMyModelClassToImportInstances.setFont(font)
        self.lblSelectMyModelClassToImportInstances.setWordWrap(True)
        self.lblSelectMyModelClassToImportInstances.setObjectName(_fromUtf8("lblSelectMyModelClassToImportInstances"))
        self.gridLayout_4.addWidget(self.lblSelectMyModelClassToImportInstances, 0, 0, 1, 3)
        WizardSearchByInstanceLabel.addPage(self.wizardPage2)
        self.wizardPage3 = QtGui.QWizardPage()
        self.wizardPage3.setTitle(_fromUtf8(""))
        self.wizardPage3.setObjectName(_fromUtf8("wizardPage3"))
        self.gridLayout_2 = QtGui.QGridLayout(self.wizardPage3)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.lblShowPropertiesOfBothModels = QtGui.QLabel(self.wizardPage3)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lblShowPropertiesOfBothModels.setFont(font)
        self.lblShowPropertiesOfBothModels.setWordWrap(True)
        self.lblShowPropertiesOfBothModels.setObjectName(_fromUtf8("lblShowPropertiesOfBothModels"))
        self.gridLayout_2.addWidget(self.lblShowPropertiesOfBothModels, 0, 0, 1, 1)
        self.tableWidgetViewPropertiesOfBothModels = QtGui.QTableWidget(self.wizardPage3)
        self.tableWidgetViewPropertiesOfBothModels.setAutoFillBackground(False)
        self.tableWidgetViewPropertiesOfBothModels.setEditTriggers(QtGui.QAbstractItemView.NoEditTriggers)
        self.tableWidgetViewPropertiesOfBothModels.setAlternatingRowColors(True)
        self.tableWidgetViewPropertiesOfBothModels.setSelectionMode(QtGui.QAbstractItemView.NoSelection)
        self.tableWidgetViewPropertiesOfBothModels.setObjectName(_fromUtf8("tableWidgetViewPropertiesOfBothModels"))
        self.tableWidgetViewPropertiesOfBothModels.setColumnCount(2)
        self.tableWidgetViewPropertiesOfBothModels.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.tableWidgetViewPropertiesOfBothModels.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidgetViewPropertiesOfBothModels.setHorizontalHeaderItem(1, item)
        self.tableWidgetViewPropertiesOfBothModels.horizontalHeader().setCascadingSectionResizes(False)
        self.tableWidgetViewPropertiesOfBothModels.horizontalHeader().setDefaultSectionSize(300)
        self.tableWidgetViewPropertiesOfBothModels.horizontalHeader().setMinimumSectionSize(300)
        self.tableWidgetViewPropertiesOfBothModels.horizontalHeader().setStretchLastSection(True)
        self.gridLayout_2.addWidget(self.tableWidgetViewPropertiesOfBothModels, 1, 0, 1, 1)
        WizardSearchByInstanceLabel.addPage(self.wizardPage3)
        self.wizardPage4 = QtGui.QWizardPage()
        self.wizardPage4.setEnabled(True)
        self.wizardPage4.setTitle(_fromUtf8(""))
        self.wizardPage4.setObjectName(_fromUtf8("wizardPage4"))
        self.gridLayout = QtGui.QGridLayout(self.wizardPage4)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.lblPopulatedInstances = QtGui.QLabel(self.wizardPage4)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lblPopulatedInstances.setFont(font)
        self.lblPopulatedInstances.setWordWrap(True)
        self.lblPopulatedInstances.setObjectName(_fromUtf8("lblPopulatedInstances"))
        self.gridLayout.addWidget(self.lblPopulatedInstances, 0, 0, 1, 1)
        self.treeWidgetSummary = QtGui.QTreeWidget(self.wizardPage4)
        self.treeWidgetSummary.setContextMenuPolicy(QtCore.Qt.CustomContextMenu)
        self.treeWidgetSummary.setAlternatingRowColors(True)
        self.treeWidgetSummary.setSelectionMode(QtGui.QAbstractItemView.NoSelection)
        self.treeWidgetSummary.setSelectionBehavior(QtGui.QAbstractItemView.SelectRows)
        self.treeWidgetSummary.setAllColumnsShowFocus(False)
        self.treeWidgetSummary.setObjectName(_fromUtf8("treeWidgetSummary"))
        self.treeWidgetSummary.header().setVisible(False)
        self.gridLayout.addWidget(self.treeWidgetSummary, 1, 0, 1, 1)
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.lineEditSearchTreeSummary = QtGui.QLineEdit(self.wizardPage4)
        self.lineEditSearchTreeSummary.setEnabled(True)
        self.lineEditSearchTreeSummary.setObjectName(_fromUtf8("lineEditSearchTreeSummary"))
        self.horizontalLayout_5.addWidget(self.lineEditSearchTreeSummary)
        self.btnExpandAll_Summary = QtGui.QPushButton(self.wizardPage4)
        self.btnExpandAll_Summary.setEnabled(True)
        self.btnExpandAll_Summary.setMinimumSize(QtCore.QSize(53, 0))
        self.btnExpandAll_Summary.setMaximumSize(QtCore.QSize(53, 16777215))
        self.btnExpandAll_Summary.setObjectName(_fromUtf8("btnExpandAll_Summary"))
        self.horizontalLayout_5.addWidget(self.btnExpandAll_Summary)
        self.btnCollapseAll_Summary = QtGui.QPushButton(self.wizardPage4)
        self.btnCollapseAll_Summary.setEnabled(True)
        self.btnCollapseAll_Summary.setMinimumSize(QtCore.QSize(53, 0))
        self.btnCollapseAll_Summary.setMaximumSize(QtCore.QSize(53, 16777215))
        self.btnCollapseAll_Summary.setObjectName(_fromUtf8("btnCollapseAll_Summary"))
        self.horizontalLayout_5.addWidget(self.btnCollapseAll_Summary)
        self.gridLayout.addLayout(self.horizontalLayout_5, 2, 0, 1, 1)
        WizardSearchByInstanceLabel.addPage(self.wizardPage4)

        self.retranslateUi(WizardSearchByInstanceLabel)
        self.comboBoxSearchLanguage.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(WizardSearchByInstanceLabel)

    def retranslateUi(self, WizardSearchByInstanceLabel):
        WizardSearchByInstanceLabel.setWindowTitle(_translate("WizardSearchByInstanceLabel", "Search by Instance Label - Step 1", None))
        self.lblSearchInstanceLabelInEM.setText(_translate("WizardSearchByInstanceLabel", "Search for instances with label in External Model", None))
        self.lineEditSearchInstanceLabelInEMClassName.setToolTip(_translate("WizardSearchByInstanceLabel", "Type the label of the class to search for in External Model", None))
        self.lineEditSearchInstanceLabelInEMClassName.setPlaceholderText(_translate("WizardSearchByInstanceLabel", "Search External Model...", None))
        self.btnSearchInstanceLabelInEM.setText(_translate("WizardSearchByInstanceLabel", "Search", None))
        self.radioButtonExactMatch.setToolTip(_translate("WizardSearchByInstanceLabel", "Search for labels matching the exact term", None))
        self.radioButtonExactMatch.setText(_translate("WizardSearchByInstanceLabel", "Exact match", None))
        self.radioButtonContainsTerm.setToolTip(_translate("WizardSearchByInstanceLabel", "Search for labels containing the term", None))
        self.radioButtonContainsTerm.setText(_translate("WizardSearchByInstanceLabel", "Contains term", None))
        self.checkBoxCaseSensitive.setToolTip(_translate("WizardSearchByInstanceLabel", "Make search case sensitive", None))
        self.checkBoxCaseSensitive.setText(_translate("WizardSearchByInstanceLabel", "Case sensitive", None))
        self.comboBoxSearchLanguage.setToolTip(_translate("WizardSearchByInstanceLabel", "Search for results in a specific language", None))
        self.comboBoxSearchLanguage.setItemText(0, _translate("WizardSearchByInstanceLabel", "None", None))
        self.comboBoxSearchLanguage.setItemText(1, _translate("WizardSearchByInstanceLabel", "English, en", None))
        self.treeWidgetSearchInstanceLabelInEMInstancesResults.setWhatsThis(_translate("WizardSearchByInstanceLabel", "Instances found in external model - Please select one or more Instances to import to my model", None))
        self.treeWidgetSearchInstanceLabelInEMInstancesResults.headerItem().setText(0, _translate("WizardSearchByInstanceLabel", "Instances", None))
        self.treeWidgetSearchInstanceLabelInEMInstancesResults.headerItem().setText(1, _translate("WizardSearchByInstanceLabel", "Value", None))
        self.btnAllPage1.setToolTip(_translate("WizardSearchByInstanceLabel", "Select all", None))
        self.btnAllPage1.setText(_translate("WizardSearchByInstanceLabel", "All", None))
        self.btnNonePage1.setToolTip(_translate("WizardSearchByInstanceLabel", "Select none", None))
        self.btnNonePage1.setText(_translate("WizardSearchByInstanceLabel", "None", None))
        self.lineEditSearchTreePage1.setPlaceholderText(_translate("WizardSearchByInstanceLabel", "Search tree...", None))
        self.btnExpandAll.setText(_translate("WizardSearchByInstanceLabel", "Expand", None))
        self.btnCollapseAll.setText(_translate("WizardSearchByInstanceLabel", "Collapse", None))
        self.lblSearching.setText(_translate("WizardSearchByInstanceLabel", "Searching...", None))
        self.comboBoxMyModelClasses.setToolTip(_translate("WizardSearchByInstanceLabel", "Select a class from My Model where selected instances will be imported", None))
        self.comboBoxMyModelClasses.setWhatsThis(_translate("WizardSearchByInstanceLabel", "Select a class of my model to import new instances", None))
        self.lblSelectMyModelClassToImportInstances.setText(_translate("WizardSearchByInstanceLabel", "Select a class from My Model", None))
        self.lblShowPropertiesOfBothModels.setText(_translate("WizardSearchByInstanceLabel", "Match properties of My Model and External Model", None))
        self.tableWidgetViewPropertiesOfBothModels.setToolTip(_translate("WizardSearchByInstanceLabel", "Property Mapping table - Please match My Model properties to External Model properties", None))
        self.tableWidgetViewPropertiesOfBothModels.setWhatsThis(_translate("WizardSearchByInstanceLabel", "Property mapping - Please match my model properties to external model properties", None))
        item = self.tableWidgetViewPropertiesOfBothModels.horizontalHeaderItem(0)
        item.setText(_translate("WizardSearchByInstanceLabel", "Properties of External Model", None))
        item = self.tableWidgetViewPropertiesOfBothModels.horizontalHeaderItem(1)
        item.setText(_translate("WizardSearchByInstanceLabel", "Properties of My Model", None))
        self.lblPopulatedInstances.setText(_translate("WizardSearchByInstanceLabel", "TextLabel", None))
        self.treeWidgetSummary.setWhatsThis(_translate("WizardSearchByInstanceLabel", "Instances found in external model - Please select one or more Instances to import to my model", None))
        self.treeWidgetSummary.headerItem().setText(0, _translate("WizardSearchByInstanceLabel", "Instances", None))
        self.treeWidgetSummary.headerItem().setText(1, _translate("WizardSearchByInstanceLabel", "Value", None))
        self.lineEditSearchTreeSummary.setPlaceholderText(_translate("WizardSearchByInstanceLabel", "Search tree...", None))
        self.btnExpandAll_Summary.setText(_translate("WizardSearchByInstanceLabel", "Expand", None))
        self.btnCollapseAll_Summary.setText(_translate("WizardSearchByInstanceLabel", "Collapse", None))

import search_by_instance_label_wizard_resources_rc
